### ISSUE TITLE
Create add_maven_dep tool

### ISSUE THREAD

**Issue by oferb** [google/startup-os#166]
The tool should be under `tools` and do these 2 steps:
1. Add Maven dependency to dependencies.yaml:
https://github.com/google/startup-os/blob/master/commands.txt#L14
2. Regenerate dependencies:
https://github.com/google/startup-os/blob/master/commands.txt#L24

**Comment by NikleshPhabiani** [comment]
Hello. I am just starting to contribute towards open source projects and found StartupOS to be an interesting one to start with. I would really like to work on this issue but would need guidance on how to get started with it. I am also going through some bits of the existing code and documentation in order to get a knack of it. Thanks.

**Comment by oferb** [comment]
Great!
So this task is basically to create a bash script that accepts `<maven_artifact>`, passes it to the command in the first link above, and then runs the command in the second link.
You can place it under `tools`.

**Comment by NikleshPhabiani** [comment]
Great! Thank you very much. I have created a bash script and would like to go ahead and create a pull request for the same but would need permission for it.

**Comment by vmax** [comment]
@NikleshPhabiani you can [fork](https://help.github.com/articles/fork-a-repo/) this repo and submit your changes from there

**Comment by NikleshPhabiani** [comment]
Done. Thanks a lot for the assistance @oferb and @vmax . I appreciate it. Getting used to the environment.

**Comment by oferb** [comment]
Thanks Niklesh for your help!
This is now fixed.
