### ISSUE TITLE
Thinking task: multi-repo CI

### ISSUE THREAD

**Issue by oferb** [google/startup-os#287]
Now that we have a basic multi-repo cli, multi-repo Code Review, think about how we can do multi-repo CI. Say we have `startup-os` and `hasadna` as the 2 repos. Author presses submit after approval in Reviewer, to a diff that changes both repos. Now what do we do to push the changes to both repos, and make `hasadna` point to the new commit in startup-os?

**Comment by oferb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Thinking task: multi-repo CI](https://trello.com/c/dGIuzdee/5-thinking-task-multi-repo-ci)

**Comment by lloydchang** [comment]
> Now what do we do to push the changes to both repos, and make hasadna point to the new commit in startup-os?

Hi @oferb, the following should trigger multi-repo CI:

**startup-os:**
```
git commit
git push
```

**hasadna:**
```
git submodule add https://github.com/google/startup-os
git submodule foreach git pull
git commit
git push
```

**Comment by oferb** [comment]
Thanks!
I also considered submodules, but 2 things got me thinking maybe it would be better to write a mechanism to do it:
1. It's only for git, so won't work with Mercurial and other VCSs.
2. People don't seem to like them for some reason (haven't used them myself to have an opinion): https://news.ycombinator.com/item?id=17055919

I thought of a manifest file that contains a list of repo URLs and commit shas.

Max has done some work on having CI clone a repo and put it in a folder that another repo can then depend on. Setting it up to a particular commit is needed to be able to test, well, a particular commit :)

If you're interested in trying to implement the manifest file mechanism (I can guide you on the implementation, using protocol buffers and Java), let me know :)

**Comment by lloydchang** [comment]
Thank you @oferb and @vmax

Perhaps I don't understand the why? for the problem you want to solve.

1. I interpreted this #287 as a thinking task, and not an implementation task at all.
2. Thanks for asking, but I'm not interested in trying to implement a new manifest file mechanism because industry standard tools already support continuous integration (CI) of multiple repositories.

A. For small projects, a manifest can be implemented via revision control tools such as Mercurial and Git.

B. For large projects with tightly coupled repositories, a manifest can be implemented at higher levels of abstraction via Repo, Bazel, etc.

C. For microservices architecture with loosely coupled services in multiple repositories, consider Jenkins X for Kubernetes for continuous integration.

---

For what it's worth, here's related information as food for thought :-)

• `.hgsub` nesting several VCSes (Mercurial, Git and Subversion) sub-repositories https://www.mercurial-scm.org/repo/hg/help/subrepos
> Mercurial currently supports Mercurial, Git, and Subversion subrepositories.
> 
> Subrepositories let you nest external repositories or projects into a parent Mercurial repository, and make commands operate on them as a group.

• `git submodule` https://blog.github.com/2016-02-01-working-with-submodules/
> Before you add a repository as a submodule, first check to see if you have a better alternative available.
> 
> Git submodules work well enough for simple cases, but these days there are often better tools available for managing dependencies than what Git submodules can offer.
> 
> Modern languages like Go have friendly, Git-aware dependency management systems built-in from the start. Others, like Ruby’s rubygems, Node.js’ npm, or Cocoa’s CocoaPods and Carthage, have been added by the programming community. Even front-end developers have tools like Bower to manage libraries and frameworks for client-side JavaScript and CSS.

• `git subtree` https://developer.atlassian.com/blog/2015/05/the-power-of-git-subtree/
> Git subtree allows you to insert any repository as a sub-directory of another one. It is one of several ways Git projects can manage project dependencies.

• Git Repo https://gerrit.googlesource.com/git-repo/
> Repo is a tool built on top of Git. Repo helps manage many Git repositories, does the uploads to revision control systems, and automates parts of the development workflow. Repo is not meant to replace Git, only to make it easier to work with Git.

• Bazel external dependencies https://docs.bazel.build/versions/master/external.html
> If you want to use targets from a second Bazel project, you can use local_repository, git_repository or http_archive to symlink it from the local filesystem, reference a git repository or download it (respectively).

• Jenkins X: Git Servers https://jenkins-x.io/developing/git/
> Jenkins X defaults to using GitHub, the free public git hosting solution for open source projects.
> However when working in the enterprise you may wish to use different git servers.

• Opinionated Kubernetes and Jenkins X
https://jenkins.io/blog/2018/04/10/opinionated-cd-jenkins-x/
> Jenkins X is a Kubernetes-native continuous integration and continuous delivery platform for developing cloud native applications.
> 
> The best experience initially is using Google’s excellent GKE service:
> `jx create cluster gke`

**Comment by oferb** [comment]
Thanks!
Wow, I really appreciate this. Looks like you have plenty experience in VCSs :)
This is indeed a thinking task, and you didn't "sign up" for anything :), so it's ok. Any help/advice is welcome.
In our current scheme, there is one "master" repo, but the other repos are not subfolders but rather siblings under one parent folder. Some of the options treat subrepos as subfolders, so that's no suitable.

Once repos are "side by side", it's up to the build tool to handle that. For example, Bazel's `local_repository` which you mentioned.

As an extension, we will also support easily switching from `http_archive` to `local_repository`, so that people can clone one repo and still get things working. If they see that they're breaking something in another repo, they'd have the best experience by using the multi-repo tools we're building (multi-repo Code Review, cli and CI) to make the change.

**Comment by oferb** [comment]
Thinking about this more, I think by now we have a pretty good idea of how to implement this, so I'm closing this issue. Feel free to continue to respond if you have more comments/ideas.

**Comment by oferb** [comment]
Thinking about this more, I think by now we have a pretty good idea of how to implement this, so I'm closing this issue. Feel free to continue to respond if you have more comments/ideas.
