### ISSUE TITLE
Single directory for testing.

### ISSUE THREAD

**Issue by yanivsn** [google/startup-os#30]
Hi,

I would like to suggest having some kind of a centralized place directory which will hold all the tests. This is order to separate tests from code, and having an easy way of finding one's class tests.
 
The suggested idea is as such:

Have a test directory at the root of the project, on each added class have a corresponding test class under the test directory, where the path underneath the test class will correspond to the path of the original class.

For example, lets say we have the following project:
```
startupos/
  code_reviewer/
    some_feature/
      SomeInteface.java
      SomeImpl.java
```

the matching test directory will look as such:
```
startupos/
  tests/
    code_reviewer/
      some_feature/
        SomeImplTest.java
```

What do you think?

**Comment by oferb** [comment]
I'd rather have the tests closer to the code - i.e
```
startupos/
  code_reviewer/
    some_feature/
      SomeInteface.java
      SomeImpl.java
      tests/
        SomeImplTest.java
```

Having tests in a completely separate directory makes it hard to see if you have a corresponding test for a class than if the test is in a `tests` subdirectory. In tree folder views in IDE's and in OS file explorers it's "far away", and in the terminal you can't effectively use `cd` to get there.

**Comment by jbduncan** [comment]
As an external observer, I think @yanivsn's proposal makes the most sense.

It's very common practice in the world of Java (1) for tests to be in the same _package_ as the code they're testing, and (2) for non-test code to be under a `src/main/java` directory and test code to be under a `src/test/java`.

The benefit of following (1) is that complex implementation details can easily be tested without exposing them to external users by making them package-private.

Furthermore, the benefit of following (2) or maybe even a scheme very similar to it (like @yanivsn's suggestion or Guava's code layout) is that most other open source and Maven/Gradle projects already follow this pattern, and thus people new to StartupOS can easily find their way through the code.

That's just my two cents. :)

**Comment by jbduncan** [comment]
@oferb 

> I find both of them rather confusing. The separation for the reasons I mentioned before, and the long folder structure - because it's just so very long.

I used to think too that that folder structure was too long. But I've grown used to it now (I know, not a very good reason!). However, as I'm personally a Gradle user, I see an advantage to it: if one wants to introduce, say, [Refaster](http://errorprone.info/docs/refaster) templates, then one can put them under `src/refaster/java` and tell Gradle about it by declaring it as a new source set. This prevents placing them amongst the actual Java source files and accidentally having the Refaster templates compiled into a user-facing jar where they're not supposed to be.

Also, thinking from the perspective of new users who encounter StartupOS and come from Maven and Gradle (which AFAIK are still by far the most popular Java builds tools to date), I suspect that when they want to re-use aspects of StartupOS for their own projects, the test-folder-directly-under-source-file scheme is going to be quite confusing, as it doesn't map cleanly to the `src/test/java` convention. (I'm not even sure if Maven and Gradle support having tests organised and run under this test-folder-directly-under-source-file scheme...)

> Where do you put the C++ and python tests?

I'd make an educated guess that, following the Maven convention, they'd go under `src/test/cpp` and `src/test/python`.

FWIW, Bazel itself seems to organise code it's C++ code under a `src/main/cpp` directory. I don't know the reasoning for why they do this, but I'm tempted to think it has something to do with Bazel's Java code being under a similar `src/main/java` directory.

> The conventions there are (AFAIK) for tests to be in a subfolder.

Ah okay, I didn't know that! (Goes to show that I hardly do development outside of Java... :stuck_out_tongue_winking_eye:)

> Another use-case is jvm languages, which are less common but interop with java, so the connection is stronger. So where do you put scala code, or kotlin code?

I believe there are two widely-used conventions: one is to put Scala and Kotlin code under `src/main/scala` and `src/main/kotlin` respectively, another is to put them both under `src/main/java` (but I think that's prone to certain problems - I'm not familiar enough with Scala and Kotlin to know what problems those are).

> About the prefix src/main/java/com/google/startupos/, I don't see a compelling reason to keep it. I have a theory (that I've never checked) that the reason for this is that a Java jar could not (until Java 9 modules) use 2 classes with the same name and package. So one way of preventing collisions between packages was to preface the domain name (com.google.startupos), and also tie it to the uniqueness of files in the filesystem (i.e you can't have 2 files with the same name in the same folder). This is no longer the case in Java 9 onwards.

Somehow I seriously doubt that's correct.

Java modules are recommended to follow a similar reverse-DNS naming structure to packages (http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) for a number of reasons, and split-packages (packages that are used in two or more projects) still cause problems in the module world.

That's why people have problems incorporating different projects that share the `javax.annotation.*` package, like JSR-305, into their projects post-Java 8 (https://blog.codefx.org/java/jsr-305-java-9/). I believe it's also partially why Guava is investigating the Checker Framework's annotations as an alternative to JSR-305 (https://github.com/google/guava/issues/2960).

Thus, if we even just get rid of the `com.google.startupos` prefix from package names for the Java-related stuff in StartupOS, I'm certain it will cause problems in the long term. (_Maybe_ having just a `startupos` prefix will do, but then we'd be risking the small possibility that another Java project is also named StartupOS and we'd then have to change to `com.google.startupos` anyway.)

> One final note - is that with bazel you can easily get the targets you're looking for using the bazel query command:
bazel query //... --output label_kind
So you could really easily get all the java_binary or cpp_binary targets, or java_test, without having it in separate folders.
Another final note - with bazel you don't have to keep the folders and the packages aligned, so you could have the tests in the ../tests folder actually be in the same package as the tested code.

Cool, didn't know about this either!

So does this mean that, with Bazel, you could organise Java code in such a way that, to give a theoretical example, a Java-package-private `src/common/Splitter.java` class could then be accessed by a `src/common/tests/SplitterTest.java` test class? Or does it not work like that and would `src/common/Splitter.java` be have to be made Java-`public`?

**Comment by oferb** [comment]
You raise some good points. Let me think about them, follow the links etc.
Bazel doesn't look at the package names, and java doesn't look at the folder structure.
So it works out :) You can put java files in different directories and have them belong to the same package.

**Comment by jbduncan** [comment]
> You raise some good points. Let me think about them, follow the links etc.

:+1: Please take your time. My response was very long, so I'll happily and patiently wait. :)

> Bazel doesn't look at the package names, and java doesn't look at the folder structure.
So it works out :) You can put java files in different directories and have them belong to the same package.

Oh cool, I never knew before that Java doesn't actually look at the folder structure to e.g. check that package names and relative folders match up. One learns something everyday!

**Comment by oferb** [comment]
Ok, here's my reply, to your reply :)
* Refaster is really cool! Have you used it?
* I don't worry about non-product code getting into the product. For one, there are many types of non-product code besides tests - server liveness prober, data cleaning tools, various administration tools, development tools like refaster. Some of those are sometimes placed in `src`. Also, having rafaster etc get into product code, while not desired, is just going to enlarge your jar a little bit. There's a lot of classes in your jar you're not using. If you use proguard etc then probably it'll even get stripped out.
* About people who encounter StartupOS, I hope they'll appreciate this sensible structure :) If they're copy pasting snippets or a few select files, they would be fine with it. I don't think many people would copy large directory structures and not just fork the whole repo. Note that Bazel allows for using specific BUILD targets from another repo.
* If you think about it - we have 2 "attributes" here - language (java), aspect (test, src) and also hierarchical project organization, and we're trying to fit it all into a hierarchical folder structure. There's no "right" way.
* People do use multiple languages in a project, and projects can have multiple aspects.
* About the packages - I think we should check to see if it works to keep the current folder structure, and just change the packages to have the `com.google.startupos` prefix. If it does, based on what you wrote I think it's a good idea to have that prefix.

**Comment by oferb** [comment]
As an FYI, you can find all targets of a certain type by:
`bazel query //... --output label_kind | grep java_binary`
So even if the folders contain mixed language files, you can easily extract the ones you're looking for.

**Comment by jbduncan** [comment]
@oferb Sorry for the delayed response! I'll respond to your last two messages inline. :)

> - Refaster is really cool! Have you used it?

Yep! I'm currently experimenting with it by building an unpublished and undocumented Gradle plugin over at https://github.com/jbduncan/jupiter-collection-testers/tree/master/buildSrc. :)

> - I don't worry about non-product code getting into the product. For one, there are many types of non-product code besides tests - server liveness prober, data cleaning tools, various administration tools, development tools like refaster. Some of those are sometimes placed in src. Also, having rafaster etc get into product code, while not desired, is just going to enlarge your jar a little bit. There's a lot of classes in your jar you're not using. If you use proguard etc then probably it'll even get stripped out.

Okay, these are all fair points!

> - About people who encounter StartupOS, I hope they'll appreciate this sensible structure :) If they're copy pasting snippets or a few select files, they would be fine with it. I don't think many people would copy large directory structures and not just fork the whole repo. Note that Bazel allows for using specific BUILD targets from another repo.

Again, these are all fair points.

> - If you think about it - we have 2 "attributes" here - language (java), aspect (test, src) and also hierarchical project organization, and we're trying to fit it all into a hierarchical folder structure. There's no "right" way.

Again, fair point!

> - People do use multiple languages in a project, and projects can have multiple aspects.

Of course. :)

> - About the packages - I think we should check to see if it works to keep the current folder structure, and just change the packages to have the `com.google.startupos` prefix. If it does, based on what you wrote I think it's a good idea to have that prefix.

Hmm... My gut reaction is to keep the old packages, because otherwise it's going to be confusing for me (and other people, I suspect) as I'm so used to thinking that the package and relative directory of a Java source file has to be the same.

Furthermore, package-private stuff in package A could then be accessed by stuff in package B if they were merged together, which would weaken encapsulation; and that weakened encapsulation would be very obscure to people such as myself who are used to being able to determine the package of a Java file from its directory.

Overall, I argue that even just changing all the packages to just `com.google.startupos` without also changing the directories would be very confusing.

> As an FYI, you can find all targets of a certain type by:
bazel query //... --output label_kind | grep java_binary
So even if the folders contain mixed language files, you can easily extract the ones you're looking for.

SGTM!

To wrap up, I'm reasonably happy now with the decision behind the test-folder-under-every-Java-file scheme, but if I've understood things correctly, I still have reservations about having all Java files share the same package `com.google.startupos` without changing their directories.

**Comment by oferb** [comment]
Ok, SGTM too!
